### ISSUE TITLE
Examples aren't working

### ISSUE THREAD

**Issue by vincecampanale** [joezimjs/Webpack-Introduction-Tutorial#3]
Hi Joe! 
Thanks for putting together this tutorial. It's a great read, but none of the examples run correctly. Whether I use your github repo and checkout the branch or write the code myself. Here's the content of the npm-debug.log: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vince/.nvm/versions/node/v7.7.3/bin/node',
1 verbose cli   '/home/vince/.nvm/versions/node/v7.7.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webpack-intro-tut@1.0.0~prestart: webpack-intro-tut@1.0.0
6 silly lifecycle webpack-intro-tut@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle webpack-intro-tut@1.0.0~start: webpack-intro-tut@1.0.0
8 verbose lifecycle webpack-intro-tut@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-intro-tut@1.0.0~start: PATH: /home/vince/.nvm/versions/node/v7.7.3/lib/node_modules/npm/bin/node-gyp-bin:/home/vince/Tutorials/Webpack-Introduction-Tutorial/node_modules/.bin:/home/vince/.nvm/versions/node/v7.7.3/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0:/usr/lib/llvm/4/bin:/home/vince/.rvm/bin:/home/vince/.rvm/bin:/home/vince/.rvm/bin
10 verbose lifecycle webpack-intro-tut@1.0.0~start: CWD: /home/vince/Tutorials/Webpack-Introduction-Tutorial
11 silly lifecycle webpack-intro-tut@1.0.0~start: Args: [ '-c', 'npm run build -s && npm run execute -s' ]
12 silly lifecycle webpack-intro-tut@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle webpack-intro-tut@1.0.0~start: Failed to exec start script
14 verbose stack Error: webpack-intro-tut@1.0.0 start: `npm run build -s && npm run execute -s`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/vince/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/vince/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid webpack-intro-tut@1.0.0
16 verbose cwd /home/vince/Tutorials/Webpack-Introduction-Tutorial
17 error Linux 4.10.9-gentoo
18 error argv "/home/vince/.nvm/versions/node/v7.7.3/bin/node" "/home/vince/.nvm/versions/node/v7.7.3/bin/npm" "start"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error webpack-intro-tut@1.0.0 start: `npm run build -s && npm run execute -s`
22 error Exit status 1
23 error Failed at the webpack-intro-tut@1.0.0 start script 'npm run build -s && npm run execute -s'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack-intro-tut package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build -s && npm run execute -s
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack-intro-tut
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack-intro-tut
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joezimjs** [comment]
Ok. I'll look into it. Note, I do not have a Linux system, so it may have something to do with that, but I don't see why it should.

**Comment by joezimjs** [comment]
A few questions:

1) Are you in the master branch? Meaning are you at the last step, or is this happening in an earlier step?
2) Did you `npm install` all of the dependencies?
3) The `&&` operator does work in your OS's console, right?

I re-downloaded the entire repo, `npm install`ed and ran `npm start` and it all worked just fine for me on my machine, so I can't determine the issue.

**Comment by joezimjs** [comment]
I just ran it using Cloud 9 IDE, which is an online, Linux-based machine, and it worked just fine.

**Comment by vincecampanale** [comment]
Sorry for the delay - I was on the master branch, had `install`ed all dependencies, and I believe the `&&` operator works but I'm not sure. I'm on Gentoo.  

It's probably just me. Thanks for taking the time to look into this and if I get a chance I'll go back and look again. The TDD tutorial was awesome! Definitely looking forward to applying the concepts on the project we are starting at work. 

As someone who also writes technical posts, I know the work that goes into it so thank you.
